# Generated by Django 2.2 on 2019-04-21 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmsurvey', '0003_auto_20190421_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('scale', 'Scale'), ('dicotomic', 'Dicotomic')], default='scale', max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='scale_question',
            name='choice',
        ),
        migrations.DeleteModel(
            name='Dicotomic_Question',
        ),
        migrations.DeleteModel(
            name='Scale_Question',
        ),
    ]
