# Generated by Django 2.1.7 on 2019-04-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kmsurvey', '0005_auto_20190422_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='approach',
            name='description',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tool',
            name='description',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
